name: artifact_deployed
 
on:
  # workflow_dispatch is mandatory, so that Artifactory can trigger
  # the workflow through GitHub REST API.
  workflow_dispatch:
    # inputs are optional, they may be used to convey contextual data
    # from the JFrog event to the workflow.
    inputs:
      artifact_path:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print artifact_path
        run: echo  The path is ${{ inputs.artifact_path }}
       
      - name: Notify slack success
        if: success()
        env:
         SLACK_BOT_TOKEN: xapp-1-A04TPAK73TK-4928616816947-6c145404cad69c4b7e2d0841cdd83dada009ff9fbc6509a2cfc395cc790c5b32
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
         channel: app-alerts
         status: SUCCESS
         color: good
