name: artifact_deployed
 
on:
  # workflow_dispatch is mandatory, so that Artifactory can trigger
  # the workflow through GitHub REST API.
  workflow_dispatch:
    # inputs are optional, they may be used to convey contextual data
    # from the JFrog event to the workflow.
    inputs:
      artifact_path:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print artifact_path
        id: job_one
        run: echo  The path is ${{ inputs.artifact_path }}
       
      - name: Check on failures
        env:
         SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        if: steps.job_one.outcome == 'success'
        run: |
         curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' "${SLACK_BOT_TOKEN}"
